VANDERMONDE MATRIX GENERATION:

FIRST APPROACH

In [2]:
import numpy as np
X = np.array([1,2,3,5])
N = 3
val = np.vander(X, N)
print('Matrix using built-in vander method: ')
print('{}'.format(val))

Matrix using built-in vander method: 
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


SECOND APPROACH

In [4]:
import numpy as np
X = np.array([1,2,3,5])
N = 3
val = np.column_stack([X**(N-1-i) for i in range(N)])
print('Matrix using built-in column_stack method: ')
print('{}'.format(val))

Matrix using built-in column_stack method: 
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
